name: gravitee

config-version: 2
version: '0.0.1'

# Need to Check With Team To Ensure That Custom Profiles Are Not Supported
profile: fivetran_dbt

require-dbt-version: [">=0.17.0", "<=0.18.0"]

# See Quoting Docs for Snowflake
# https://docs.getdbt.com/reference/project-configs/quoting
quoting:
  database: false
  schema: false
  identifier: false

vars:
  fivetran_log:
      unioning_multiple_destinations: false # disables macro for combining multiple destinations' Log Connectors"
      account: "{{ source('fivetran_log', 'account') }}" 
      account_membership: "{{ source('fivetran_log', 'account_membership') }}"
      active_volume: "{{ source('fivetran_log', 'active_volume') }}"
      connector: "{{ source('fivetran_log', 'connector') }}"  
      credits_used: "{{ source('fivetran_log', 'credits_used') }}"
      destination: "{{ source('fivetran_log', 'destination') }}"
      destination_membership: "{{ source('fivetran_log', 'destination_membership') }}" 
      log: "{{ source('fivetran_log', 'log') }}" 
      transformation: "{{ source('fivetran_log', 'transformation') }}"
      trigger_table: "{{ source('fivetran_log', 'trigger_table') }}"
      user: "{{ source('fivetran_log', 'user') }}"

  zendesk_source:
    zendesk_database: reporting-299920
    zendesk_schema: zendesk
    using_schedules: false        # Disable if you do not have the schedule and ticket_schedule tables, or if you do not want metrics reported in business hours
    using_sla_policy: false       # Disable if you are not using SLAs 
  
  zendesk:
    zendesk_database: reporting-299920
    zendesk_schema: zendesk
    using_schedules: false
    using_sla_policy: false

  salesforce:
    salesforce_database: reporting-299920
    salesforce_schema: salesforce
    
  google_ads-source:
    zendesk_database: reporting-299920
    zendesk_schema: adwords
    
  google_ads:
    zendesk_database: reporting-299920
    zendesk_schema: adwords


# prevents empty trigger and transformations form being created if they do not exist
# set to true if you still wish for them to be created
models:
  fivetran_log:
    fivetran_log_transformation_status:
      +enabled: false
    staging:
      stg_fivetran_log_trigger_table:
        +enabled: false
      stg_fivetran_log_transformation:
        +enabled: false
