jobs:

- name: fivetran_log
  schedule: '*/5 * * * *'
  steps:
    - name: run fivetran log 
      command: dbt run --models fivetran_log 

- name: zendesk
  schedule: '*/5 * * * *'
  steps:
    - name: run zendesk 
      command: dbt run --models +zendesk
      
- name: hubspot
  schedule: '*/5 * * * *'
  steps:
    - name: run hubspot models 
      command: dbt run --models +hubspot
      
- name: google_ads
  schedule: '*/5 * * * *'
  steps:
    - name: run google_ads models 
      command: dbt run --models +google_ads

# - name: specifictime815ampst
#   schedule: 15 8 * * *
#   steps:
#     - name: run models 
#       command: dbt run --target dev

# - name: every55minutes
#   schedule: '*/5 * * * *'
#   steps:
#     - name: run models 
#       command: dbt run --target dev
